import type { InferGetStaticPropsType } from "next";
import Head from "next/head";
import Image from "next/image";

export async function getStaticProps() {
  try {
    const rbrRes = await fetch(
      "https://api.github.com/repos/react-brasil/vagas/issues?state=open&per_page=50"
    );
    const fbrRes = await fetch(
      "https://api.github.com/repos/frontendbr/vagas/issues?state=open&per_page=50"
    );
    const rbr = await rbrRes.json();
    const fbr = await fbrRes.json();

    return {
      props: {
        data: [...rbr, ...fbr],
      },
    };
  } catch (error) {
    console.log(error);
  }
}

const Home = ({ data }: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
