name: CI

on: [push, pull_request]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: Borales/actions-yarn@v4.1.0
        with:
          cmd: install

      - name: Build
        uses: Borales/actions-yarn@v4.1.0
        with:
          cmd: build

      - name: Tests
        uses: Borales/actions-yarn@v4.1.0
        with:
          cmd: test